### ISSUE TITLE
Make jar Multi-Release

### ISSUE THREAD

**Issue by Kamillaova** [AlexProgrammerDE/SoulFire#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

Add `Multi-Release: true` entry to MANIFEST.MF
This will fix `WARNING: Runtime environment or build system does not support multi-release JARs. This will impact location-based features.`

### How can we reproduce what you got?

Just launch SoulFire/ServerWrecker

### SoulFire Version

any?

### Java Version

21

**Comment by AlexProgrammerDE** [comment]
![image](https://github.com/AlexProgrammerDE/SoulFire/assets/40795980/b58b383a-2f5d-412d-b16d-eb80f52d1503)
Seems like some dependencies really provide multi-release classes. I'll add the flag, thanks!
