### ISSUE TITLE
Make every bot move to a different random location

### ISSUE THREAD

**Issue by Moutard3** [AlexProgrammerDE/SoulFire#341]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Currently we can make bots move to an x/z position, it could be useful for testing chunk loading/unloading to be able to make every bot move to a different random location.

**Comment by AlexProgrammerDE** [comment]
I've now added a command to dev builds to make every bot go to a random position within a set radius: https://github.com/AlexProgrammerDE/SoulFire/commit/6725c0c273b104f10c770ce4cc1b2b1674916115
