### ISSUE TITLE
Proxy Parse from url every attack / Proxy URL support

### ISSUE THREAD

**Issue by erxson** [AlexProgrammerDE/SoulFire#361]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

1. It would be cool if proxies automatically parsed every attack from a specific link of proxy scraper.
2. It would also be cool to add support for shuffled (socks4 + socks5) lists in URL format. Example:
```
socks5://123.123.123.123:443
socks5://321.321.321.321:1080
socks4://132.132.132.132:52435
socks4://312.312.312.312:4145
```
The point of the URL format support is that the most popular proxy checker from monosans generates such a file. Well, if you combine two types of proxies, then you get almost twice as many proxies as if you chose only a specific type. (translated with gogla translata)

**Comment by AlexProgrammerDE** [comment]
The latest dev build now supports this feature.

**Comment by AlexProgrammerDE** [comment]
Oh wait nevermind, I only added the URI proxy feature, the feature to fetch proxies for every attack from a URL is not planned for now.
