### ISSUE TITLE
Unregistered serverbound packet class

### ISSUE THREAD

**Issue by waterghost-2046** [AlexProgrammerDE/SoulFire#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

I can't connect 1.20.1

### How can we reproduce what you got?

just connect 1.20.1 with offline bot

### SoulFire/Error Logs

https://gist.github.com/waterghost-2046/945fbee7f4ff672549150d3f90840d18

### SoulFire Version

latest

### Java Version

openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment Corretto-21.0.4.7.1 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.4.7.1 (build 21.0.4+7-LTS, mixed mode, sharing)

**Comment by AlexProgrammerDE** [comment]
Should be fixed
