### ISSUE TITLE
🤖 | Able to add Refresh tokens as accounts

### ISSUE THREAD

**Issue by Satanaelcode** [AlexProgrammerDE/SoulFire#564]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I want to be able to use Refresh tokens to add accounts to the Soulfire Server

**Comment by AlexProgrammerDE** [comment]
Pretty sure that's even possible with the library I'm using. May I ask how you obtain refresh tokens? Where are they stored/where do you get them?

**Comment by AlexProgrammerDE** [comment]
Gotcha, I'll look into it.

**Comment by AlexProgrammerDE** [comment]
Done with https://github.com/AlexProgrammerDE/SoulFire/commit/0bca8e3531bb36a94e82c28a6a7183a9129f490d
You'll see the new option in the next update.

**Comment by AlexProgrammerDE** [comment]
Released with https://github.com/AlexProgrammerDE/SoulFire/releases/tag/1.14.0
