### ISSUE TITLE
Custom Usernames just straight-up don't work & Can't connect more than 1 bot

### ISSUE THREAD

**Issue by Shivter14** [AlexProgrammerDE/SoulFire#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

I'm really frustrated. Whenever I try connecting more than 1 bot, they all have the same username (Bot_1) thus only 1 can join. No matter what parameters I give it, no matter what account list I give it, it just either connects only 1 bot, or tries connecting the same bot multiple times.

### How can we reproduce what you got?

literally just try using `--bot-amount` and it will only use `Bot_1` as the username and try to connect with the same name multiple times.

### SoulFire Version

1.15.0

### Java Version

openjdk version "21.0.5" 2024-10-15

**Comment by AlexProgrammerDE** [comment]
Found the cause of the issue, next release should hopefully fix it.

**Comment by Shivter14** [comment]
I switched to just using the client & integrated server, and the new update seems to have fixed it.
